name: PR Merge

on:
  #pull_request:
  #  types:
  #    - synchronize # prにcommit がpushされた時
  #    - opened # prがopenされた時
  #    - ready_for_review # draft → prに変更された時
  #    - reopened # closeされたprが再度openした時
  #  paths:
  #    - '.github/ISSUE_TEMPLATE/**'
  #    - '.github/PULL_REQUEST_TEMPLATE.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-merge:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Merge Pull Request
        run: |
          gh pr merge $PR_URL --merge

